### ISSUE TITLE
How to train a linear AU classifier from the learned embedding?

### ISSUE THREAD

**Issue by yy19931029** [mysee1989/TCAE#8]
Hello, sorry to ask you again, your paper said to transform the AU result, you trained a linear AU classifier from the learned embedding. Can you tell me which dataset you used? Do you have the model or the code for training?

**Comment by mysee1989** [comment]
Please refer to the experimental section in the original paper.

**Comment by putao537** [comment]
In the section of "Evaluation protocols",  you wrote "We trained a linear AU classifier from the learned embedding".  Can I understand it as you have used the au labels of the target dataset‘s train set to train AU classifier? If it is, I don't understand where is "Self-supervised Representation Learning"; Otherwise, can you explain precisely the process of training AU classifier? After all, you only used one sentence to describe this process in this paper.
